plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pixelboss.office'
    compileSdk 34

    defaultConfig {
        applicationId "com.pixelboss.office"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    // 使用本地 SDK
    lint {
        abortOnError false
    }
}
